import os


def set_enviroment():
    """Create subdirectories needed for the other steps of the pipeline.

    Directory tree after work of the pipeline will look like this (except for .py files):
    .
    ├── cd_hit - folder with cd-hit results
    ├── data - folder where all the genomes and output files will be saved
    │   ├── assembly_summary.txt - table with all organism assemblies from refseq.
    │   ├── GCF_000005845.2_ASM584v2 - folder with files for that assembly
    │   │   ├── GCF_000005845.2_ASM584v2_db_alignment.csv - generated by align_to_db()
    │   │   ├── GCF_000005845.2_ASM584v2_feature_table.txt - from NCBI
    │   │   ├── GCF_000005845.2_ASM584v2_genomic.fna - from NCBI
    │   │   ├── GCF_000005845.2_ASM584v2_protein.faa - from NCBI
    │   │   └── GCF_000005845.2_ASM584v2_protein.gpff - from NCBI
    │   ├── GCF_000006665.1_ASM666v1
    │   ...
    ├── logs
    │   ├── alignment.log - log of align_to_database()
    │   ├── database.log - log of create_database()
    │   ├── downloading.log - log of download_genomes()
    │   └── pipeline.log - general log
    └── plots - folder with graphs

    """
    os.makedirs('cd_hit', exist_ok=True)
    os.makedirs('data', exist_ok=True)
    os.makedirs('plots', exist_ok=True)
    os.makedirs('logs', exist_ok=True)
